---
abstract: 'Ketama Consistent Hashing for Perl (XS)'
author:
  - 'Christian Muehlhaeuser C<< <chris@last.fm> >>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.84
  Test::Requires: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-ConsistentHash-Ketama
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0.1
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.00001_02
